apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-test
  namespace: default
spec:
  replicas: 10
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
      - name: stress
        image: polinux/stress
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        command: ["stress"]
        args:
        - "--cpu"
        - "1"
        - "--io"
        - "1"
        - "--vm"
        - "1"
        - "--vm-bytes"
        - "256M"
        - "--timeout"
        - "600s"
      nodeSelector:
        pool: example-nodepool
