apiVersion: v2
name: nodepool
description: A Helm chart for Multi-Cloud Kubernetes Autoscaler Operator
type: application
version: 0.1.2
appVersion: "0.1.2"
keywords:
  - hetzner
  - hcloud
  - kubernetes
  - nodepool
  - autoscaler
  - operator
home: https://github.com/autokubeio/nodepool
sources:
  - https://github.com/autokubeio/nodepool
maintainers:
  - name: Mahyar Moghadam
    url: https://github.com/autokubeio
